### ISSUE TITLE
functional manpage

### ISSUE THREAD

**Issue by degieusz** [jeaye/stdman#34] opened 2019-06-17 13:27 UTC
i cant find way to access https://en.cppreference.com/w/cpp/header/functional, it seems its missing

steps to reproduce:
man functional
man std::functional

**Comment by jeaye** [comment] 2019-06-24 18:33
stdman doesn't provide man pages for whole headers right now, just individual functions, classes, etc. This is effectively a duplicate of #5.

**Closed by jeaye** 2019-06-24 18:33 UTC
